"""Run an author's own code as a reference, and keep the per-seed numbers.

`mmsa_reference.py` does this for the fourteen models MMSA implements. Methods
that MMSA never included -- everything from 2024 onward -- have only their
authors' releases, so this is the parallel runner for those. Kept separate
rather than folded in: MMSA is one codebase invoked through one API, while each
author release has its own entry point, and mixing them would make the stable
path hostage to the unstable one.

    python scripts/author_reference.py run dpdf_lq 42 43 44 45 46 47 48 49 50 51
    python scripts/author_reference.py collect

Two disciplines are carried over verbatim from `mmsa_reference.py`, because
both were paid for:

* **Every run records the machine that produced it.** MMSA's code turned out to
  be as machine-bound as ours -- tfn seed 42 moves 0.0136 MAE between an RTX
  5070 Ti and a 5080 -- so a reference whose provenance is unrecorded cannot be
  paired with anything.
* **`collect` refuses to merge across machines.** A per-seed value conflict is
  caught anyway, but two machines can disagree *without* colliding: one
  contributes seeds 42-46 and the other 47-51, the merge succeeds, and the
  resulting distribution exists on no machine at all.

The results land in `docs/author_code_runs_mosi.json`, deliberately separate
from MMSA's file. Two reference sources with different provenance do not belong
in one table.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import threading
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = PROJECT_ROOT / "author_runs"          # git-ignored, like mmsa_runs
RUNS_PATH = PROJECT_ROOT / "docs" / "author_code_runs_mosi.json"
DATASETS = PROJECT_ROOT / "datasets" / "CMU-MOSI" / "Processed"

#: DLF has no command line. This calls its own `DLF_run` with our pickle and one
#: seed, and is written out as a file rather than passed to `python -c` so that a
#: traceback points at readable source. `featurePath` is absolute here: the
#: release joins its `dataset_root_dir` on at config-load time and then applies
#: `config` over the result (run.py:82-91), so this replaces the joined path.
DLF_DRIVER = '''"""Generated by scripts/author_reference.py -- do not edit here."""
import sys

import torch.optim.lr_scheduler as _sched

# PyTorch removed ReduceLROnPlateau's `verbose` argument (deprecated in 2.2, gone
# by 2.6) and the release still passes verbose=True, so it cannot start at all on
# a current torch. Patched here rather than in the release, which stays
# read-only. The argument only ever controlled whether a line was printed when
# the rate dropped -- it reaches no tensor, so this changes no number. Any
# *other* incompatibility would be a real difference and must not be papered
# over this way.
_ReduceLROnPlateau = _sched.ReduceLROnPlateau


class _CompatPlateau(_ReduceLROnPlateau):
    def __init__(self, *args, verbose=False, **kwargs):
        super().__init__(*args, **kwargs)


_sched.ReduceLROnPlateau = _CompatPlateau

from run import DLF_run  # noqa: E402  -- imported after the patch, on purpose

seed = int(sys.argv[1])
DLF_run(
    model_name="DLF", dataset_name="mosi", is_tune=False, seeds=[seed],
    config={"featurePath": {features!r}},
    model_save_dir="./pt", res_save_dir="./result", log_dir="./log",
    mode="train", is_training=True,
)
'''

#: Their metric names -> ours, per method: two releases derived from the same
#: framework still print different names, and DLF's `acc_2` is not DPDF-LQ's.
#: All are fractions on both sides; nothing is rescaled anywhere in this file.
METRIC_KEYS = {
    "MAE": "mae", "Corr": "corr",
    "Non0_acc_2": "acc2_non0", "Non0_F1_score": "f1_non0",
    "Has0_acc_2": "acc2_has0", "Has0_F1_score": "f1_has0",
    "Mult_acc_5": "acc5", "Mult_acc_7": "acc7",
}
#: DLF ships two metric implementations and its trainer imports the second one,
#: `trains/utils/metricsTop.py` -- not the MMSA-standard `utils/metricsTop.py`
#: also in the checkout, which is dead. The names below are that file's, and its
#: `acc_2`/`F1_score` are the NON-ZERO variants (it drops neutral samples before
#: binarising), so they map to acc2_non0/f1_non0. Reading the other file would
#: have silently mislabelled them; the dead copy has no Corr and no acc_5, which
#: is what gave it away.
DLF_METRIC_KEYS = {
    "MAE": "mae", "Corr": "corr", "acc_2": "acc2_non0",
    "F1_score": "f1_non0", "acc_5": "acc5", "acc_7": "acc7",
}

#: One entry per method. `repo` is where its release is checked out, `command`
#: is how that release trains one seed, and `metrics` maps its own metric names
#: onto ours. Nothing inside a release is edited; anything that has to be
#: adjusted goes here, in the open.
METHODS = {
    "dpdf_lq": {
        "repo": Path("/workspace/DPDF-LQ"),
        "features": "aligned_50.pkl",
        "config": "configs/mosi.yaml",
        "command": ["python", "train.py", "--config_file", "{config}", "--seed", "{seed}"],
        "log": {"valid": "Validation Results:", "test": "Test Results:"},
        "paper": "Dual-Path Dynamic Fusion with Learnable Query, EMNLP 2025",
        "licence": "MIT",
    },
    "dlf": {
        "repo": Path("/workspace/DLF"),
        "features": "aligned_50.pkl",
        # No CLI: the release exposes `DLF_run(...)`, the signature it inherited
        # from MMSA. `driver` is written next to the logs and run with the repo
        # as the working directory -- calling the release's own entry point
        # without editing a line of it.
        "driver": DLF_DRIVER,
        "command": ["python", "{driver}", "{seed}"],
        # Its logger prefixes every line with "MMSA - ", so these are searched
        # for anywhere in the line rather than at the start.
        "log": {"valid": "VAL-(DLF)", "test": "TEST-(DLF)", "pattern": "bare"},
        "metrics": DLF_METRIC_KEYS,
        # trains/singleTask/DLF.py:169 saves ./pt/<dataset>_<epoch>.pth on EVERY
        # epoch and deletes none of them. At BERT size that is ~440MB an epoch
        # against a 200-epoch cap: it fills any disk this instance could have
        # long before a seed ends, so this one cannot wait for the between-seed
        # sweep and gets reaped while it runs.
        "reap": "pt",
        "paper": "Disentangled-Language-Focused Multimodal Sentiment Analysis, AAAI 2025",
        "licence": "MIT",
    },
}
#: Releases print their metrics in two shapes, so the shape is per method.
#: "quoted" is a dict repr, including the numpy wrappers DPDF-LQ emits, e.g.
#: 'MAE': np.float32(0.7226). "bare" is DLF's `dict_to_str`: MAE: 0.7226.
RESULT_LINE = {
    "quoted": re.compile(r"'(\w+)':\s*(?:np\.\w+\()?(-?\d+\.?\d*)"),
    "bare": re.compile(r"\b(\w+):\s*(-?\d+\.?\d*)"),
}


def machine_fingerprint() -> dict[str, object]:
    import torch

    from msa.repro import collect_env

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    env = collect_env(device)
    return {key: env[key] for key in
            ("device_description", "cpu", "cpu_capability", "torch", "python")}


#: Refuse to start below this. Sized from the measured peak, not from caution:
#: DPDF-LQ's release deletes the superseded checkpoint before writing the next
#: (train.py:92-93), so one seed holds at most one -- about 800MB for a model
#: with a BERT per path -- and this runner clears it between seeds. Three
#: gigabytes is roughly three times the peak. The first batch still filled a
#: 16GB disk, because nothing deleted anything at all.
MIN_FREE_GB = 3


def free_gigabytes(path: Path) -> float:
    usage = shutil.disk_usage(path)
    return usage.free / 1024 ** 3


def drop_checkpoints(directory: Path) -> None:
    """Delete a release's checkpoints, keeping its logs.

    `mmsa_reference.py` has done this from the start -- its comment records that
    eleven BERT-sized models once filled the disk mid-batch. This runner was
    written without that discipline and repeated the failure at the first
    opportunity: DPDF-LQ builds a BERT per path, so one checkpoint is ~800MB and
    it saves one on every improvement.
    """
    freed = 0
    for pattern in ("*.pth", "*.pt", "*.ckpt", "*.bin"):
        for checkpoint in directory.rglob(pattern):
            freed += checkpoint.stat().st_size
            checkpoint.unlink()
    if freed:
        # The deleted bytes are not free until the writer's handles close, and
        # checking too soon reads a stale figure -- the first batch tripped its
        # own 2GB abort immediately after freeing 2.7GB.
        os.sync()
        time.sleep(2)
        print(f"  removed {freed / 1e9:.1f}GB of checkpoints", flush=True)


class _Reaper(threading.Thread):
    """Delete a release's per-epoch checkpoints while it is still training.

    `drop_checkpoints` between seeds is enough for a release that keeps one
    checkpoint at a time. DLF keeps all of them -- one per epoch, none deleted --
    so between-seed cleanup would run long after the disk was full.

    Only files untouched for `GRACE` seconds are removed, which leaves the one
    being written alone. Deleting an open file is safe on Linux anyway (the
    writer keeps the inode), but the margin costs nothing and makes the
    behaviour obvious to whoever reads this next.
    """

    GRACE = 30
    INTERVAL = 15

    def __init__(self, directory: Path) -> None:
        super().__init__(daemon=True)
        self.directory = directory
        self.done = threading.Event()
        self.freed = 0

    def run(self) -> None:
        while not self.done.wait(self.INTERVAL):
            self.sweep()

    def sweep(self) -> None:
        cutoff = time.time() - self.GRACE
        for checkpoint in self.directory.glob("*.pth"):
            try:
                if checkpoint.stat().st_mtime < cutoff:
                    self.freed += checkpoint.stat().st_size
                    checkpoint.unlink()
            except FileNotFoundError:
                pass    # the release replaced it between the stat and the unlink

    def stop(self) -> None:
        self.done.set()
        self.join(timeout=5)


def run(method: str, seeds: list[int], out_root: Path) -> None:
    spec = METHODS[method]
    repo = spec["repo"]
    if not repo.exists():
        raise SystemExit(f"no checkout at {repo}; clone the release first")
    free = free_gigabytes(repo)
    if free < MIN_FREE_GB:
        raise SystemExit(
            f"{free:.1f}GB free, need {MIN_FREE_GB}GB. A release that checkpoints "
            f"every improvement will fill this before the batch ends; clear space "
            f"first rather than discovering it at seed 7.")

    out = out_root / method
    out.mkdir(parents=True, exist_ok=True)
    # Point the release at our pickles -- the same tensors every group in this
    # repository reads -- through whichever route it offers, never by editing
    # its loader. A YAML config file for one, its own entry point for the other.
    fields: dict[str, str] = {}
    if "config" in spec:
        fields["config"] = json_safe_config(repo, spec, out)
    if "driver" in spec:
        driver = out / "driver.py"
        driver.write_text(spec["driver"].replace(
            "{features!r}", repr(str(DATASETS / spec["features"]))))
        fields["driver"] = str(driver.resolve())

    environment = dict(os.environ)
    shim = environment.get("MMSA_SHIM", "/workspace/mmsa_env/shim")
    environment["PYTHONPATH"] = os.pathsep.join(
        [shim, str(repo), environment.get("PYTHONPATH", "")])

    for seed in seeds:
        command = [part.format(seed=seed, **fields) for part in spec["command"]]
        command[0] = sys.executable
        print(f"=== {method} seed {seed}", flush=True)
        log = out / f"seed{seed}.log"
        reaper = _Reaper(repo / spec["reap"]) if "reap" in spec else None
        if reaper:
            (repo / spec["reap"]).mkdir(exist_ok=True)
            reaper.start()
        try:
            with log.open("w") as handle:
                subprocess.run(command, cwd=repo, env=environment,
                               stdout=handle, stderr=subprocess.STDOUT, check=False)
        finally:
            if reaper:
                reaper.stop()
                print(f"  reaped {reaper.freed / 1e9:.1f}GB during the seed", flush=True)
        # After every seed, not after the batch: the point is to never hold more
        # than one seed's checkpoints at a time.
        drop_checkpoints(repo)
        if free_gigabytes(repo) < 2:
            raise SystemExit(
                f"under 2GB free after seed {seed}; stopping before the disk "
                f"fills. Logs so far are in {out}.")
    (out / "machine.json").write_text(
        json.dumps(machine_fingerprint(), indent=2) + "\n")


def json_safe_config(repo: Path, spec: dict, out: Path) -> str:
    """Copy the release's config with only the data path repointed."""
    import yaml

    original = yaml.safe_load((repo / spec["config"]).read_text())
    original["dataset"]["dataPath"] = str(DATASETS / spec["features"])
    target = out / "config.yaml"
    target.write_text(yaml.safe_dump(original, sort_keys=False))
    return str(target.resolve())


def parse_log(path: Path, method: str) -> dict[str, float] | None:
    """The test metrics of the epoch chosen by VALIDATION MAE.

    This cannot be read off the release's own summary lines, and using them
    would silently import a different protocol. DPDF-LQ's `results_recorder`
    keeps two summaries and both select on the test set:

    * `best_results_one_epoch` picks the epoch with the best *test* MAE;
    * `best_results_all_epochs` is worse still -- each metric takes its own best
      epoch, so the Acc-2, MAE and Acc-7 it prints can come from three different
      models.

    Convention 2 here is that selection sees only validation data and the test
    set is touched once, afterwards. So rather than edit the release --
    references are read-only -- the honest number is rebuilt from its own
    per-epoch log: take the epoch with the lowest validation MAE and report that
    epoch's test metrics. Same run, same code, our selection rule.

    DLF needs no such reconstruction -- `KeyEval: Loss` and its trainer's
    criterion is `nn.L1Loss` over the validation set, so its own rule already
    *is* selection by validation MAE. Rebuilding it here anyway keeps one code
    path, and turns that agreement into something checked rather than assumed.
    """
    markers = METHODS[method]["log"]
    pattern = RESULT_LINE[markers.get("pattern", "quoted")]
    keys = METHODS[method].get("metrics", METRIC_KEYS)
    epochs: list[tuple[float, dict[str, float]]] = []
    validation: dict[str, float] | None = None
    for line in path.read_text(errors="ignore").splitlines():
        if markers["valid"] in line:
            validation = _metrics(line, pattern, keys)
        elif markers["test"] in line and validation is not None:
            test = _metrics(line, pattern, keys)
            if "mae" in validation and test:
                epochs.append((validation["mae"], test))
            validation = None
    if not epochs:
        return None
    return min(epochs, key=lambda pair: pair[0])[1]


def _metrics(line: str, pattern: re.Pattern[str],
             keys: dict[str, str]) -> dict[str, float]:
    found = dict(pattern.findall(line))
    return {ours: round(float(found[theirs]), 6)
            for theirs, ours in keys.items() if theirs in found}


def collect(out_root: Path) -> None:
    payload = json.loads(RUNS_PATH.read_text()) if RUNS_PATH.exists() else {"models": {}}
    models = payload.get("models", {})
    for method in sorted(METHODS):
        directory = out_root / method
        if not directory.exists():
            continue
        machine_file = directory / "machine.json"
        machine = (json.loads(machine_file.read_text()).get("device_description")
                   if machine_file.exists() else None)
        stored = models.get(method, {}).get("machine")
        if stored is not None and machine is not None and stored != machine:
            raise SystemExit(
                f"{method}: stored runs came from {stored!r}, these from {machine!r}.\n"
                f"Rerun this method's whole seed set on one machine rather than "
                f"merging two.")

        runs = dict(models.get(method, {}).get("runs", {}))
        for log in sorted(directory.glob("seed*.log")):
            seed = log.stem.removeprefix("seed")
            metrics = parse_log(log, method)
            if metrics is None:
                print(f"  skip {log.name}: no metric line found")
                continue
            if seed in runs and runs[seed] != metrics:
                raise SystemExit(
                    f"{method} seed {seed}: {log} disagrees with what is stored.\n"
                    f"  stored: {runs[seed]}\n  log:    {metrics}")
            runs[seed] = metrics
        if not runs:
            continue
        models[method] = {
            "paper": METHODS[method]["paper"],
            "licence": METHODS[method]["licence"],
            "machine": machine,
            "seeds": sorted(int(s) for s in runs),
            "n": len(runs),
            "runs": dict(sorted(runs.items(), key=lambda kv: int(kv[0]))),
        }
        print(f"  {method:10s} {len(runs)} seed(s)")

    RUNS_PATH.write_text(json.dumps({
        "source": "our own runs of each method's unmodified author release",
        "why": ("Methods published after MMSA stopped adding models have no "
                "third-party reference. Running the authors' own code on our "
                "data, our seeds and our machine is the only way to tell an "
                "implementation gap from a protocol gap."),
        "how": ("scripts/author_reference.py run <method> <seeds>, then collect. "
                "Nothing inside a release is edited; the only adjustment is the "
                "dataset path, applied through the release's own config file."),
        "models": dict(sorted(models.items())),
    }, indent=2, ensure_ascii=False) + "\n")
    print(f"\nwrote {RUNS_PATH.relative_to(PROJECT_ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    sub = parser.add_subparsers(dest="command", required=True)
    run_cmd = sub.add_parser("run")
    run_cmd.add_argument("method", choices=sorted(METHODS))
    run_cmd.add_argument("seeds", nargs="+", type=int)
    sub.add_parser("collect")
    args = parser.parse_args()

    if args.command == "run":
        run(args.method, args.seeds, args.out)
    else:
        collect(args.out)


if __name__ == "__main__":
    main()
