"""Run an author's own code as a reference, and keep the per-seed numbers.

`mmsa_reference.py` does this for the fourteen models MMSA implements. Methods
that MMSA never included -- everything from 2024 onward -- have only their
authors' releases, so this is the parallel runner for those. Kept separate
rather than folded in: MMSA is one codebase invoked through one API, while each
author release has its own entry point, and mixing them would make the stable
path hostage to the unstable one.

    python scripts/author_reference.py run dpdf_lq 42 43 44 45 46 47 48 49 50 51
    python scripts/author_reference.py collect

Two disciplines are carried over verbatim from `mmsa_reference.py`, because
both were paid for:

* **Every run records the machine that produced it.** MMSA's code turned out to
  be as machine-bound as ours -- tfn seed 42 moves 0.0136 MAE between an RTX
  5070 Ti and a 5080 -- so a reference whose provenance is unrecorded cannot be
  paired with anything.
* **`collect` refuses to merge across machines.** A per-seed value conflict is
  caught anyway, but two machines can disagree *without* colliding: one
  contributes seeds 42-46 and the other 47-51, the merge succeeds, and the
  resulting distribution exists on no machine at all.

The results land in `docs/author_code_runs_mosi.json`, deliberately separate
from MMSA's file. Two reference sources with different provenance do not belong
in one table.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import threading
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = PROJECT_ROOT / "author_runs"          # git-ignored, like mmsa_runs
RUNS_PATH = PROJECT_ROOT / "docs" / "author_code_runs_mosi.json"
DATASETS = PROJECT_ROOT / "datasets" / "CMU-MOSI" / "Processed"

#: DLF has no command line. This calls its own `DLF_run` with our pickle and one
#: seed, and is written out as a file rather than passed to `python -c` so that a
#: traceback points at readable source. `featurePath` is absolute here: the
#: release joins its `dataset_root_dir` on at config-load time and then applies
#: `config` over the result (run.py:82-91), so this replaces the joined path.
DLF_DRIVER = '''"""Generated by scripts/author_reference.py -- do not edit here."""
import sys

import torch.optim.lr_scheduler as _sched

# PyTorch removed ReduceLROnPlateau's `verbose` argument (deprecated in 2.2, gone
# by 2.6) and the release still passes verbose=True, so it cannot start at all on
# a current torch. Patched here rather than in the release, which stays
# read-only. The argument only ever controlled whether a line was printed when
# the rate dropped -- it reaches no tensor, so this changes no number. Any
# *other* incompatibility would be a real difference and must not be papered
# over this way.
_ReduceLROnPlateau = _sched.ReduceLROnPlateau


class _CompatPlateau(_ReduceLROnPlateau):
    def __init__(self, *args, verbose=False, **kwargs):
        super().__init__(*args, **kwargs)


_sched.ReduceLROnPlateau = _CompatPlateau

from run import DLF_run  # noqa: E402  -- imported after the patch, on purpose

seed = int(sys.argv[1])
DLF_run(
    model_name="DLF", dataset_name="mosi", is_tune=False, seeds=[seed],
    config={"featurePath": {features!r}},
    model_save_dir="./pt", res_save_dir="./result", log_dir="./log",
    mode="train", is_training=True,
)
'''

#: Their metric names -> ours, per method: two releases derived from the same
#: framework still print different names, and DLF's `acc_2` is not DPDF-LQ's.
#: All are fractions on both sides; nothing is rescaled anywhere in this file.
METRIC_KEYS = {
    "MAE": "mae", "Corr": "corr",
    "Non0_acc_2": "acc2_non0", "Non0_F1_score": "f1_non0",
    "Has0_acc_2": "acc2_has0", "Has0_F1_score": "f1_has0",
    "Mult_acc_5": "acc5", "Mult_acc_7": "acc7",
}
#: DLF ships two metric implementations and its trainer imports the second one,
#: `trains/utils/metricsTop.py` -- not the MMSA-standard `utils/metricsTop.py`
#: also in the checkout, which is dead. The names below are that file's, and its
#: `acc_2`/`F1_score` are the NON-ZERO variants (it drops neutral samples before
#: binarising), so they map to acc2_non0/f1_non0. Reading the other file would
#: have silently mislabelled them; the dead copy has no Corr and no acc_5, which
#: is what gave it away.
DLF_METRIC_KEYS = {
    "MAE": "mae", "Corr": "corr", "acc_2": "acc2_non0",
    "F1_score": "f1_non0", "acc_5": "acc5", "acc_7": "acc7",
}

#: DMD needs three patches to run at all, and they are NOT of equal weight. The
#: first changes what is computed; the other two do not. Keeping them apart in
#: one place is the point -- see docs/investigations.md#dmd-reference-patches.
DMD_DRIVER = '''"""Generated by scripts/author_reference.py -- do not edit here."""
import sys

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim.lr_scheduler as _sched

EPS = 1e-12

# PATCH 1 (changes what is computed -- unavoidable, and declared).
# The trainer hands 3-D tensors to nn.CosineEmbeddingLoss. Current PyTorch
# raises "1D target tensor expects 2D input tensors", so the release cannot run
# at all. Old ATen summed over dim 1 unconditionally, which is what made those
# shapes legal; this restores exactly that and delegates every 2-D call to the
# library, so nothing else in the release changes behaviour. Our own port uses
# the same reconstruction, and scripts/check_dmd_equivalence.py asserts it
# equals PyTorch's own result on 2-D input.
_CosineEmbeddingLoss = nn.CosineEmbeddingLoss


class _LegacyCosineEmbeddingLoss(_CosineEmbeddingLoss):
    def forward(self, input1, input2, target):
        if input1.dim() <= 2:
            return super().forward(input1, input2, target)
        dot = (input1 * input2).sum(1)
        denominator = ((input1.pow(2).sum(1) + EPS)
                       * (input2.pow(2).sum(1) + EPS)).sqrt()
        cosine = dot / denominator
        positive = 1 - cosine
        negative = F.relu(cosine - self.margin)
        loss = torch.where(target.reshape(-1)[0] > 0, positive, negative)
        return loss.mean() if self.reduction == "mean" else loss.sum()


nn.CosineEmbeddingLoss = _LegacyCosineEmbeddingLoss

# PATCH 2 (cosmetic). PyTorch removed ReduceLROnPlateau's `verbose`, which only
# ever controlled whether a line was printed when the rate dropped.
_ReduceLROnPlateau = _sched.ReduceLROnPlateau


class _CompatPlateau(_ReduceLROnPlateau):
    def __init__(self, *args, verbose=False, **kwargs):
        super().__init__(*args, **kwargs)


_sched.ReduceLROnPlateau = _CompatPlateau

from run import DMD_run  # noqa: E402  -- imported after the patches, on purpose

# PATCH 3 (reporting only). This release's metric dict has no Corr, and Corr is
# one of the two primary metrics here. Selection is by validation Loss and is
# untouched; this only adds an observable to what is already logged, computed
# from the same predictions the release just scored.
import numpy as np  # noqa: E402
from trains.utils.metricsTop import MetricsTop  # noqa: E402

_get_metrics = MetricsTop.getMetics


def _with_corr(self, dataset_name):
    scorer = _get_metrics(self, dataset_name)

    def scored(y_pred, y_true):
        results = scorer(y_pred, y_true)
        pred = y_pred.view(-1).cpu().detach().numpy()
        true = y_true.view(-1).cpu().detach().numpy()
        results["Corr"] = round(float(np.corrcoef(pred, true)[0][1]), 4)
        return results

    return scored


MetricsTop.getMetics = _with_corr

seed = int(sys.argv[1])
DMD_run(
    model_name="DMD", dataset_name="mosi", is_tune=False, seeds=[seed],
    config={"featurePath": {features!r}},
    model_save_dir="./pt", res_save_dir="./result", log_dir="./log",
    mode="train", is_distill=True,
)
'''

#: DMD's live metric file (trains/utils/metricsTop.py -- it ships a second, dead
#: copy like DLF) uses capitalised names, and its acc_2/F1 are the NON-ZERO
#: variants. Corr is absent from the release and added by the driver.
DMD_METRIC_KEYS = {
    "MAE": "mae", "Corr": "corr", "Acc_2": "acc2_non0",
    "F1_score": "f1_non0", "Acc_7": "acc7",
}
#: ConFEDE runs a whole pipeline per seed: three unimodal encoders pretrained,
#: then fusion. Its config is a module rather than a file, so the driver edits
#: the module in memory -- device, seed list and the dataset path -- and calls
#: the release's own entry points.
CONFEDE_DRIVER = '''"""Generated by scripts/author_reference.py -- do not edit here."""
import sys

import torch

# PATCH (plumbing only). The release passes prefetch_factor while leaving
# num_workers at 0, which newer torch rejects outright. prefetch_factor governs
# how far ahead a worker reads and reaches no tensor value. Note what is NOT
# done here: raising num_workers instead would also satisfy torch, and would
# change how much randomness the loader draws -- see msa.data's note on exactly
# that -- so the argument is dropped rather than the worker count raised.
import torch.utils.data as _data

_DataLoader = _data.DataLoader


class _CompatDataLoader(_DataLoader):
    def __init__(self, *args, **kwargs):
        if not kwargs.get("num_workers"):
            kwargs.pop("prefetch_factor", None)
        super().__init__(*args, **kwargs)


_data.DataLoader = _CompatDataLoader

import config

config.DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
config.MOSI.path.raw_data_path = {features!r}

# PATCH (plumbing only). check_dir() makes model_path but not encoder_path, so
# stage one fails at its first save. Creating directories changes no value.
import os  # noqa: E402

for _directory in (config.MOSI.path.encoder_path, config.MOSI.path.model_path,
                   config.MOSI.path.result_path, "log"):
    os.makedirs(_directory, exist_ok=True)

seed = int(sys.argv[1])
config.seed = [seed]

from train.constrastive.Atrain import Atrain  # noqa: E402
from train.constrastive.TVA_fusion_train import (  # noqa: E402
    TVA_test_fusion,
    TVA_train_fusion,
)
from train.constrastive.Ttrain import Ttrain  # noqa: E402
from train.constrastive.Vtrain import Vtrain  # noqa: E402
from util.common import set_random_seed  # noqa: E402

set_random_seed(seed)

# Stage one, in the release's own order (main.py).
Ttrain(check={"MAE": 10000}, config=config)
Vtrain(check={"MAE": 10000}, config=config)
Atrain(check={"MAE": 10000}, config=config)

# Stage two (main-fusion.py).
TVA_train_fusion("TVA_fusion", check=config.MOSI.downStream.check,
                 load_model=config.MOSI.downStream.load_metric,
                 load_pretrain=True, config=config)
result = TVA_test_fusion("TVA_fusion",
                         check_list=config.MOSI.downStream.check_list,
                         config=config)

# Selection was on validation MAE and the test split is touched once, here --
# the release's own protocol already matches convention 2, so unlike DPDF-LQ
# there is nothing to rebuild from the logs. Printed for the parser.
print("FINAL TEST:", dict(result[config.MOSI.downStream.metric]), flush=True)
'''

#: CLGSI has a CLI but no --seeds flag (run.py hardcodes a list), and its config
#: is a module. The driver sets both and calls its own `run`, which returns the
#: test metrics of the epoch chosen by validation MAE -- already convention 2.
CLGSI_DRIVER = '''"""Generated by scripts/author_reference.py -- do not edit here."""
import sys
import types

# PATCH (plumbing only). The release imports matplotlib to plot a loss curve.
# Stubbed rather than installed: adding a package to this environment once
# dragged in a torchvision built against a different CUDA major and broke every
# BERT model in the repository. A plotting library reaches no tensor, and a stub
# cannot bring dependencies with it.
_plt = types.ModuleType("matplotlib.pyplot")
for _name in ("plot", "legend", "savefig", "figure", "close", "xlabel", "ylabel",
              "title", "clf", "show"):
    setattr(_plt, _name, lambda *a, **k: None)
_mpl = types.ModuleType("matplotlib")
_mpl.pyplot = _plt
_mpl.use = lambda *a, **k: None
sys.modules.setdefault("matplotlib", _mpl)
sys.modules.setdefault("matplotlib.pyplot", _plt)

import torch

import run as _run_module
from config.config_regression import ConfigRegression
from run import run, set_log

seed = int(sys.argv[1])


class _Args:
    pass


args = _Args()
args.train_mode = "regression"
args.modelName = "clgsi"
args.datasetName = "mosi"
args.num_workers = 0
args.model_save_dir = "results/models"
args.res_save_dir = "results/results"
args.gpu_ids = [0]
args.seeds = [seed]

config = ConfigRegression(args)
args = config.get_config()
args.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
args.dataPath = {features!r}
args.model_save_path = "results/models/clgsi-mosi-regression.pth"
args.seed = seed
args.cur_time = 1
set_log(args)
# PATCH (plumbing only). set_log builds a logger but binds it to its own local
# scope, so run() -- which calls logger.info -- finds no module-level name when
# invoked as a library rather than through __main__. Binding it back changes no
# value; without it the release cannot be driven programmatically at all.
import logging  # noqa: E402

_run_module.logger = logging.getLogger()

import numpy as np  # noqa: E402
import random  # noqa: E402

torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
np.random.seed(seed)
random.seed(seed)

result = run(args)
print("FINAL TEST:", dict(result), flush=True)
'''

#: FeaDA imports itself package-style (`import MOSI.config as cfg`) while its
#: submodules import each other flat (`from Text_encoder import ...`), so both
#: the parent and MOSI/models go on the path. Its TextEncoder hardcodes a BERT
#: path on the authors' machine, repointed here rather than edited in the tree.
FEADA_DRIVER = '''"""Generated by scripts/author_reference.py -- do not edit here."""
import os
import sys
import types

# The release mixes import styles: package-style for its own config, flat
# between its submodules. Both directories go on the path.
sys.path.insert(0, os.path.join(os.getcwd(), "MOSI", "models"))
sys.path.insert(0, os.path.join(os.getcwd(), "MOSI"))
sys.path.insert(0, os.path.join(os.getcwd(), "MOSI", "train"))
sys.path.insert(0, os.getcwd())

# PATCH (plumbing only). Stubbed rather than installed -- see the DLF/CLGSI
# entries: adding a package here once broke every BERT model in the repository.
_plt = types.ModuleType("matplotlib.pyplot")
for _name in ("plot", "legend", "savefig", "figure", "close", "xlabel", "ylabel",
              "title", "clf", "show"):
    setattr(_plt, _name, lambda *a, **k: None)
_mpl = types.ModuleType("matplotlib")
_mpl.pyplot = _plt
_mpl.use = lambda *a, **k: None
sys.modules.setdefault("matplotlib", _mpl)
sys.modules.setdefault("matplotlib.pyplot", _plt)

import torch

import MOSI.config as config

config.DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
config.MOSI.path.raw_data_path = {features!r}

# PATCH (plumbing only). Its TextEncoder points at a BERT directory on the
# authors' own filesystem. Repointed by redirecting from_pretrained rather than
# by subclassing the class: the original calls `super(TextEncoder, self)`, which
# resolves the module-level NAME, so rebinding that name makes super() find the
# subclass and recurse until the stack ends. Same weights, reachable path.
import transformers  # noqa: E402

for _cls in (transformers.BertTokenizer, transformers.BertModel):
    _original = _cls.from_pretrained
    _cls.from_pretrained = classmethod(
        lambda cls, *a, _f=_original, **k: _f("bert-base-uncased", **k))

seed = int(sys.argv[1])
config.seed = seed

from Atrain import Atrain  # noqa: E402
from data_loader import MOSIDataloader  # noqa: E402
from TVA_train import TVA_test_fusion, TVA_train_fusion  # noqa: E402
from utils import Metrics  # noqa: E402
from Vtrain import Vtrain  # noqa: E402

metrics = Metrics()
batch_size = config.MOSI.downStream.batch_size
train_data = MOSIDataloader("train", batch_size=batch_size, use_similarity=True,
                            simi_return_mono=False, num_workers=0)
valid_data = MOSIDataloader("valid", shuffle=False, num_workers=0, batch_size=batch_size)
test_data = MOSIDataloader("test", shuffle=False, num_workers=0, batch_size=batch_size)

# Stage one. The release's own main.py has these two COMMENTED OUT and calls
# only the fusion stage, which loads unimodal checkpoints the repository does
# not ship -- so its entry point cannot run as published. Uncommented here,
# which is what the README's two-stage description says to do.
Vtrain(config, metrics, seed, train_data, valid_data)
Atrain(config, metrics, seed, train_data, valid_data)
TVA_train_fusion(config, metrics, seed, train_data, valid_data)
result = TVA_test_fusion(config, metrics, test_data)
print("FINAL TEST:", dict(result) if result else {}, flush=True)
'''

#: One entry per method. `repo` is where its release is checked out, `command`
#: is how that release trains one seed, and `metrics` maps its own metric names
#: onto ours. Nothing inside a release is edited; anything that has to be
#: adjusted goes here, in the open.
METHODS = {
    "dpdf_lq": {
        "repo": Path("/workspace/DPDF-LQ"),
        "features": "aligned_50.pkl",
        "config": "configs/mosi.yaml",
        "command": ["python", "train.py", "--config_file", "{config}", "--seed", "{seed}"],
        "log": {"valid": "Validation Results:", "test": "Test Results:"},
        "paper": "Dual-Path Dynamic Fusion with Learnable Query, EMNLP 2025",
        "licence": "MIT",
    },
    "feada": {
        "repo": Path("/workspace/FeaDA-main"),
        "features": "unaligned_50.pkl",
        "driver": FEADA_DRIVER,
        "command": ["python", "{driver}", "{seed}"],
        "log": {"final": "FINAL TEST:"},
        "reap": "MOSI/save_models",
        "paper": "FeaDA, IJCNLP-AACL 2025",
        "licence": "no LICENSE file in the repository",
    },
    "clgsi": {
        "repo": Path("/workspace/CLGSI"),
        "features": "unaligned_50.pkl",
        # A real CLI, unlike the last three. `--seeds` is not one of its flags,
        # so the seed goes in through the config the runner writes.
        "driver": CLGSI_DRIVER,
        "command": ["python", "{driver}", "{seed}"],
        "log": {"final": "FINAL TEST:"},
        "reap": "results",
        "paper": "CLGSI: Contrastive Learning Guided by Sentiment Intensity, NAACL 2024 Findings",
        "licence": "MIT",
    },
    "confede": {
        "repo": Path("/workspace/ConFEDE") / "MOSI",
        "features": "unaligned_50.pkl",     # alone among these, ConFEDE is unaligned
        "driver": CONFEDE_DRIVER,
        "command": ["python", "{driver}", "{seed}"],
        # No VAL/TEST pairs to walk: the release selects on validation MAE and
        # evaluates the test split once, so its own final numbers are already
        # what convention 2 asks for.
        "log": {"final": "FINAL TEST:"},
        "reap": "ckpt",
        "paper": "ConFEDE: Contrastive Feature Decomposition, ACL 2023",
        "licence": "see repository",
    },
    "dmd": {
        "repo": Path("/workspace/DMD"),
        "features": "aligned_50.pkl",
        "driver": DMD_DRIVER,
        "command": ["python", "{driver}", "{seed}"],
        # Lower-case: this release does not upper-case model_name the way DLF does.
        "log": {"valid": "VAL-(dmd)", "test": "TEST-(dmd)", "pattern": "bare"},
        "metrics": DMD_METRIC_KEYS,
        # Saves ./pt/<epoch>.pth every epoch and deletes none, exactly like DLF
        # (trains/singleTask/DMD.py:212).
        "reap": "pt",
        "paper": "Decoupled Multimodal Distillation, CVPR 2023",
        "licence": "MIT",
    },
    "dlf": {
        "repo": Path("/workspace/DLF"),
        "features": "aligned_50.pkl",
        # No CLI: the release exposes `DLF_run(...)`, the signature it inherited
        # from MMSA. `driver` is written next to the logs and run with the repo
        # as the working directory -- calling the release's own entry point
        # without editing a line of it.
        "driver": DLF_DRIVER,
        "command": ["python", "{driver}", "{seed}"],
        # Its logger prefixes every line with "MMSA - ", so these are searched
        # for anywhere in the line rather than at the start.
        "log": {"valid": "VAL-(DLF)", "test": "TEST-(DLF)", "pattern": "bare"},
        "metrics": DLF_METRIC_KEYS,
        # trains/singleTask/DLF.py:169 saves ./pt/<dataset>_<epoch>.pth on EVERY
        # epoch and deletes none of them. At BERT size that is ~440MB an epoch
        # against a 200-epoch cap: it fills any disk this instance could have
        # long before a seed ends, so this one cannot wait for the between-seed
        # sweep and gets reaped while it runs.
        "reap": "pt",
        "paper": "Disentangled-Language-Focused Multimodal Sentiment Analysis, AAAI 2025",
        "licence": "MIT",
    },
}
#: Releases print their metrics in two shapes, so the shape is per method.
#: "quoted" is a dict repr, including the numpy wrappers DPDF-LQ emits, e.g.
#: 'MAE': np.float32(0.7226). "bare" is DLF's `dict_to_str`: MAE: 0.7226.
RESULT_LINE = {
    "quoted": re.compile(r"'(\w+)':\s*(?:np\.\w+\()?(-?\d+\.?\d*)"),
    "bare": re.compile(r"\b(\w+):\s*(-?\d+\.?\d*)"),
}


def machine_fingerprint() -> dict[str, object]:
    import torch

    from msa.repro import collect_env

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    env = collect_env(device)
    return {key: env[key] for key in
            ("device_description", "cpu", "cpu_capability", "torch", "python")}


#: Refuse to start below this. Sized from the measured peak, not from caution:
#: DPDF-LQ's release deletes the superseded checkpoint before writing the next
#: (train.py:92-93), so one seed holds at most one -- about 800MB for a model
#: with a BERT per path -- and this runner clears it between seeds. Three
#: gigabytes is roughly three times the peak. The first batch still filled a
#: 16GB disk, because nothing deleted anything at all.
MIN_FREE_GB = 3


def free_gigabytes(path: Path) -> float:
    usage = shutil.disk_usage(path)
    return usage.free / 1024 ** 3


def drop_checkpoints(directory: Path) -> None:
    """Delete a release's checkpoints, keeping its logs.

    `mmsa_reference.py` has done this from the start -- its comment records that
    eleven BERT-sized models once filled the disk mid-batch. This runner was
    written without that discipline and repeated the failure at the first
    opportunity: DPDF-LQ builds a BERT per path, so one checkpoint is ~800MB and
    it saves one on every improvement.
    """
    freed = 0
    for pattern in ("*.pth", "*.pt", "*.ckpt", "*.bin"):
        for checkpoint in directory.rglob(pattern):
            freed += checkpoint.stat().st_size
            checkpoint.unlink()
    if freed:
        # The deleted bytes are not free until the writer's handles close, and
        # checking too soon reads a stale figure -- the first batch tripped its
        # own 2GB abort immediately after freeing 2.7GB.
        os.sync()
        time.sleep(2)
        print(f"  removed {freed / 1e9:.1f}GB of checkpoints", flush=True)


class _Reaper(threading.Thread):
    """Delete a release's per-epoch checkpoints while it is still training.

    `drop_checkpoints` between seeds is enough for a release that keeps one
    checkpoint at a time. DLF keeps all of them -- one per epoch, none deleted --
    so between-seed cleanup would run long after the disk was full.

    Only files untouched for `GRACE` seconds are removed, which leaves the one
    being written alone. Deleting an open file is safe on Linux anyway (the
    writer keeps the inode), but the margin costs nothing and makes the
    behaviour obvious to whoever reads this next.
    """

    GRACE = 30
    INTERVAL = 15
    #: Per-epoch checkpoints end their name with the epoch number -- DMD writes
    #: `<epoch>.pth`, DLF writes `<dataset>_<epoch>.pth`. The *best* checkpoint
    #: has no trailing digits (`dmd.pth`, `DLFmosi.pth`) and some releases
    #: reload it when training ends, so reaping it makes the run die at the last
    #: step. Only numbered files are deleted.
    NUMBERED = re.compile(r"\d$")

    def __init__(self, directory: Path) -> None:
        super().__init__(daemon=True)
        self.directory = directory
        self.done = threading.Event()
        self.freed = 0

    def run(self) -> None:
        while not self.done.wait(self.INTERVAL):
            self.sweep()

    def sweep(self) -> None:
        cutoff = time.time() - self.GRACE
        for checkpoint in self.checkpoints():
            if not self.NUMBERED.search(checkpoint.stem):
                continue
            try:
                if checkpoint.stat().st_mtime < cutoff:
                    self.freed += checkpoint.stat().st_size
                    checkpoint.unlink()
            except FileNotFoundError:
                pass    # the release replaced it between the stat and the unlink

    def checkpoints(self):
        """Every checkpoint under the directory, at any depth.

        DLF and DMD write `*.pth` at the top level; ConFEDE writes `*.ckpt` into
        nested `ckpt/` subdirectories, and a 418MB BERT encoder per improvement.
        A pattern that fitted the first two would have swept nothing here and the
        disk would have filled again.
        """
        for pattern in ("*.pth", "*.ckpt", "*.pt"):
            yield from self.directory.rglob(pattern)

    def stop(self) -> None:
        self.done.set()
        self.join(timeout=5)


def run(method: str, seeds: list[int], out_root: Path) -> None:
    spec = METHODS[method]
    repo = spec["repo"]
    if not repo.exists():
        raise SystemExit(f"no checkout at {repo}; clone the release first")
    free = free_gigabytes(repo)
    if free < MIN_FREE_GB:
        raise SystemExit(
            f"{free:.1f}GB free, need {MIN_FREE_GB}GB. A release that checkpoints "
            f"every improvement will fill this before the batch ends; clear space "
            f"first rather than discovering it at seed 7.")

    out = out_root / method
    out.mkdir(parents=True, exist_ok=True)
    # Point the release at our pickles -- the same tensors every group in this
    # repository reads -- through whichever route it offers, never by editing
    # its loader. A YAML config file for one, its own entry point for the other.
    fields: dict[str, str] = {}
    if "config" in spec:
        fields["config"] = json_safe_config(repo, spec, out)
    if "driver" in spec:
        driver = out / "driver.py"
        driver.write_text(spec["driver"].replace(
            "{features!r}", repr(str(DATASETS / spec["features"]))))
        fields["driver"] = str(driver.resolve())

    environment = dict(os.environ)
    shim = environment.get("MMSA_SHIM", "/workspace/mmsa_env/shim")
    environment["PYTHONPATH"] = os.pathsep.join(
        [shim, str(repo), environment.get("PYTHONPATH", "")])

    for seed in seeds:
        command = [part.format(seed=seed, **fields) for part in spec["command"]]
        command[0] = sys.executable
        print(f"=== {method} seed {seed}", flush=True)
        log = out / f"seed{seed}.log"
        reaper = _Reaper(repo / spec["reap"]) if "reap" in spec else None
        if reaper:
            (repo / spec["reap"]).mkdir(exist_ok=True)
            reaper.start()
        try:
            with log.open("w") as handle:
                subprocess.run(command, cwd=repo, env=environment,
                               stdout=handle, stderr=subprocess.STDOUT, check=False)
        finally:
            if reaper:
                reaper.stop()
                print(f"  reaped {reaper.freed / 1e9:.1f}GB during the seed", flush=True)
        # After every seed, not after the batch: the point is to never hold more
        # than one seed's checkpoints at a time.
        drop_checkpoints(repo)
        if free_gigabytes(repo) < 2:
            raise SystemExit(
                f"under 2GB free after seed {seed}; stopping before the disk "
                f"fills. Logs so far are in {out}.")
    (out / "machine.json").write_text(
        json.dumps(machine_fingerprint(), indent=2) + "\n")


def json_safe_config(repo: Path, spec: dict, out: Path) -> str:
    """Copy the release's config with only the data path repointed."""
    import yaml

    original = yaml.safe_load((repo / spec["config"]).read_text())
    original["dataset"]["dataPath"] = str(DATASETS / spec["features"])
    target = out / "config.yaml"
    target.write_text(yaml.safe_dump(original, sort_keys=False))
    return str(target.resolve())


def parse_log(path: Path, method: str) -> dict[str, float] | None:
    """The test metrics of the epoch chosen by VALIDATION MAE.

    This cannot be read off the release's own summary lines, and using them
    would silently import a different protocol. DPDF-LQ's `results_recorder`
    keeps two summaries and both select on the test set:

    * `best_results_one_epoch` picks the epoch with the best *test* MAE;
    * `best_results_all_epochs` is worse still -- each metric takes its own best
      epoch, so the Acc-2, MAE and Acc-7 it prints can come from three different
      models.

    Convention 2 here is that selection sees only validation data and the test
    set is touched once, afterwards. So rather than edit the release --
    references are read-only -- the honest number is rebuilt from its own
    per-epoch log: take the epoch with the lowest validation MAE and report that
    epoch's test metrics. Same run, same code, our selection rule.

    DLF needs no such reconstruction -- `KeyEval: Loss` and its trainer's
    criterion is `nn.L1Loss` over the validation set, so its own rule already
    *is* selection by validation MAE. Rebuilding it here anyway keeps one code
    path, and turns that agreement into something checked rather than assumed.
    """
    markers = METHODS[method]["log"]
    pattern = RESULT_LINE[markers.get("pattern", "quoted")]
    keys = METHODS[method].get("metrics", METRIC_KEYS)
    if "final" in markers:
        # The release already selected on validation and touched test once; the
        # last such line is the answer. Nothing to reconstruct.
        finals = [_metrics(line, pattern, keys)
                  for line in path.read_text(errors="ignore").splitlines()
                  if markers["final"] in line]
        return finals[-1] if finals and finals[-1] else None
    epochs: list[tuple[float, dict[str, float]]] = []
    validation: dict[str, float] | None = None
    for line in path.read_text(errors="ignore").splitlines():
        if markers["valid"] in line:
            validation = _metrics(line, pattern, keys)
        elif markers["test"] in line and validation is not None:
            test = _metrics(line, pattern, keys)
            if "mae" in validation and test:
                epochs.append((validation["mae"], test))
            validation = None
    if not epochs:
        return None
    return min(epochs, key=lambda pair: pair[0])[1]


def _metrics(line: str, pattern: re.Pattern[str],
             keys: dict[str, str]) -> dict[str, float]:
    found = dict(pattern.findall(line))
    return {ours: round(float(found[theirs]), 6)
            for theirs, ours in keys.items() if theirs in found}


def collect(out_root: Path) -> None:
    payload = json.loads(RUNS_PATH.read_text()) if RUNS_PATH.exists() else {"models": {}}
    models = payload.get("models", {})
    for method in sorted(METHODS):
        directory = out_root / method
        if not directory.exists():
            continue
        machine_file = directory / "machine.json"
        machine = (json.loads(machine_file.read_text()).get("device_description")
                   if machine_file.exists() else None)
        stored = models.get(method, {}).get("machine")
        if stored is not None and machine is not None and stored != machine:
            raise SystemExit(
                f"{method}: stored runs came from {stored!r}, these from {machine!r}.\n"
                f"Rerun this method's whole seed set on one machine rather than "
                f"merging two.")

        runs = dict(models.get(method, {}).get("runs", {}))
        for log in sorted(directory.glob("seed*.log")):
            seed = log.stem.removeprefix("seed")
            metrics = parse_log(log, method)
            if metrics is None:
                print(f"  skip {log.name}: no metric line found")
                continue
            if seed in runs and runs[seed] != metrics:
                raise SystemExit(
                    f"{method} seed {seed}: {log} disagrees with what is stored.\n"
                    f"  stored: {runs[seed]}\n  log:    {metrics}")
            runs[seed] = metrics
        if not runs:
            continue
        models[method] = {
            "paper": METHODS[method]["paper"],
            "licence": METHODS[method]["licence"],
            "machine": machine,
            "seeds": sorted(int(s) for s in runs),
            "n": len(runs),
            "runs": dict(sorted(runs.items(), key=lambda kv: int(kv[0]))),
        }
        print(f"  {method:10s} {len(runs)} seed(s)")

    RUNS_PATH.write_text(json.dumps({
        "source": "our own runs of each method's unmodified author release",
        "why": ("Methods published after MMSA stopped adding models have no "
                "third-party reference. Running the authors' own code on our "
                "data, our seeds and our machine is the only way to tell an "
                "implementation gap from a protocol gap."),
        "how": ("scripts/author_reference.py run <method> <seeds>, then collect. "
                "Nothing inside a release is edited; the only adjustment is the "
                "dataset path, applied through the release's own config file."),
        "models": dict(sorted(models.items())),
    }, indent=2, ensure_ascii=False) + "\n")
    print(f"\nwrote {RUNS_PATH.relative_to(PROJECT_ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    sub = parser.add_subparsers(dest="command", required=True)
    run_cmd = sub.add_parser("run")
    run_cmd.add_argument("method", choices=sorted(METHODS))
    run_cmd.add_argument("seeds", nargs="+", type=int)
    sub.add_parser("collect")
    args = parser.parse_args()

    if args.command == "run":
        run(args.method, args.seeds, args.out)
    else:
        collect(args.out)


if __name__ == "__main__":
    main()
